### ISSUE TITLE
SparseMatrixCSC options

### ISSUE THREAD

**Issue by joshday** [joshday/StandardizedMatrices.jl#1]
Just putting this thought somewhere.  Should standard deviations be calculated using only nonzero values?  Otherwise, the more sparse a matrix is, the more inflated the standardized values will be.

**Comment by nignatiadis** [comment]
Hi, I really like the idea of this package! I think standard deviations should always be calculated using the full matrix (because otherwise it would not correspond to standard statistical notation). If someone wants to do some unconventional normalization with their sparse matrix they can still use the `StandardizedMatrix(x::AMat, μ::AVec, σ::AVec)` method. 

However, especially for the case you are describing, it could be useful to also have a simple way of just generating a centered matrix (i.e. `μ=vec(mean(x, 1))` and  `σinv = ones(p)`), especially since the centering (and not the scaling) is the culprit which destroys sparsity.

**Comment by joshday** [comment]
Thanks for your input!  I agree about using the full matrix and any special case can be left to the user.  Adding a constructor for a centered-only matrix should also be easy enough.
